### ISSUE TITLE
vtkLookupTable serializer not getting the right NumberOfColors?

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame-vtk#16]
<img width="1297" alt="Screen Shot 2023-01-26 at 10 56 41 AM" src="https://user-images.githubusercontent.com/22067021/214912572-3d2509c7-6466-48c2-b510-ecbde7e103b5.png">

I would think that `GetNumberOfColors()` is all that's needed. But maybe something in the client-side VTK.js code isn't using this?

Example code:

```py
"""Validate vtkLookupTable serializer with N Colors."""

import pyvista as pv
from trame.app import get_server
from trame.ui.vuetify import SinglePageLayout
from trame.widgets import html, vuetify
from trame.widgets.vtk import VtkLocalView, VtkRemoteView

server = get_server()
state, ctrl = server.state, server.controller

state.trame__title = "PyVista Lookup Table N Colors"

# -----------------------------------------------------------------------------
pv.set_plot_theme("document")


mesh = pv.Wavelet()

plotter = pv.Plotter(off_screen=True)
actor = plotter.add_mesh(mesh, n_colors=7)
plotter.set_background("lightgrey")
plotter.view_isometric()

# -----------------------------------------------------------------------------
# GUI
# -----------------------------------------------------------------------------

with SinglePageLayout(server) as layout:
    layout.icon.click = ctrl.view_reset_camera
    layout.title.set_text(state.trame__title)

    with layout.toolbar:
        vuetify.VSpacer()

    with layout.content:
        with vuetify.VContainer(
            fluid=True,
            classes="pa-0 fill-height",
        ):
            with vuetify.VContainer(
                fluid=True, classes="pa-0 fill-height", style="width: 50%;"
            ):
                local = VtkLocalView(
                    plotter.ren_win,
                )
            with vuetify.VContainer(
                fluid=True, classes="pa-0 fill-height", style="width: 50%;"
            ):
                remote = VtkRemoteView(
                    plotter.ren_win,
                )

            def view_update(**kwargs):
                local.update(**kwargs)
                remote.update(**kwargs)

            def view_reset_camera(**kwargs):
                local.reset_camera(**kwargs)
                remote.reset_camera(**kwargs)

            ctrl.view_update = view_update
            ctrl.view_reset_camera = view_reset_camera

            ctrl.on_server_ready.add(view_update)

    # hide footer
    layout.footer.hide()

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

if __name__ == "__main__":
    server.start()
```

**Comment by banesullivan** [comment]
To follow up `GetNumberOfColors()` is used in the serializer:

https://github.com/Kitware/VTK/blob/af0878b870528596009fc9a627a8aa9b90917316/Web/Python/vtkmodules/web/render_window_serializer.py#L780

which is why I think there might be something need on the VTK.js side to use this?

**Comment by jourdain** [comment]
Are you sure that is not [that serializer used instead?](https://github.com/Kitware/VTK/blob/af0878b870528596009fc9a627a8aa9b90917316/Web/Python/vtkmodules/web/render_window_serializer.py#L218)

**Comment by banesullivan** [comment]
Aha!! Yep that is indeed the serializer being used.

**Comment by jourdain** [comment]
I think that can be fixed on the Python side then.

**Comment by banesullivan** [comment]
I think the serializer is still doing everything right though... 

https://github.com/Kitware/VTK/blob/af0878b870528596009fc9a627a8aa9b90917316/Web/Python/vtkmodules/web/render_window_serializer.py#L812

When that helper generates the `vtkColorTransferFunction`, it indeed sets up the right number of colors. and it seems VTK.js takes that transfer function and interpolates it to have 256 colors. This is more obvious when using a Cyclic colormap and fewer N colors. Take `jet` with 2 colors for example:


![download](https://user-images.githubusercontent.com/22067021/214927073-e7f70dcd-d7fd-45bd-af14-795b2a60cf42.jpg)

<img width="1324" alt="Screen Shot 2023-01-26 at 12 05 51 PM" src="https://user-images.githubusercontent.com/22067021/214926993-60e13228-1357-4563-bbbf-6ec648ca5575.png">

by splitting the transfer function into 2 colors, we get the ends of the colormap. Red and Blue. This gets serialized. Then VTK.js seems to take that and interpolate the colors for range of 256
