### ISSUE TITLE
Expose PBR in render window serializer

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame-vtk#18]
We should expose Physically Based Rendering for the client side viewer since this is supported in VTK.js: https://www.kitware.com/introducing-physically-based-rendering-to-vtk-js-webgpu/

**Comment by jourdain** [comment]
WebGPU is not supported across browsers 

https://caniuse.com/webgpu

**Comment by jourdain** [comment]
Not going to happen any time soon. So closing for now.
