### ISSUE TITLE
The error for VTK not having the web module enabled is not user friendly

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame-vtk#2]
```
$ python trame-test.py
> VTK is not available inside your Python environment
Traceback (most recent call last):
  File "trame-test.py", line 144, in <module>
    view = vtk.VtkRemoteView(
  File "/home/local/KHQ/bane.sullivan/Software/viz-stuff/env-egl-vtk/lib/python3.8/site-packages/trame_vtk/widgets/vtk/common.py", line 531, in __init__
    self.server.state[self.__view_key_id] = MODULE.id(view)
  File "/home/local/KHQ/bane.sullivan/Software/viz-stuff/env-egl-vtk/lib/python3.8/site-packages/trame_vtk/modules/vtk/__init__.py", line 175, in id
    return HELPER.id(vtk_obj)
AttributeError: 'NoneType' object has no attribute 'id'
```

The check and failure in 

https://github.com/Kitware/trame-vtk/blob/c9b7cef7ebf897763f2424416cff4c875b526f12/trame_vtk/modules/vtk/__init__.py#L1-L8

Is not descriptive enough for new users and the actual error that happens is not insightful for what is going wrong.

Considering the the VTK on conda-forge still does not have the needed module enabled, this error could turn away a lot of new users from the software.

I suggest a few things:

1. Change the `print` statement to an actual warning
2. On `__init__` for any of the VTK widget classes in trame, check `has_vtk` and raise a meaningful error to point users in the right direction
3. Change the message given to something about needing the web module rather than a blanket "VTK is not available" as VTK can be installed perfectly well but miss the module trame requires. The fact that VTK has different modules that can be enabled or not is an **advanced** topic the majority of Python users aren't going to dabble into

On a related note, if trame is a core platform from Kitware then we should consider merging the web module in VTK into the Core of VTK to avoid these issues altogether.

**Comment by banesullivan** [comment]
Related https://github.com/conda-forge/vtk-feedstock/pull/258

In case users are googling this error and this issue pops up. You will need to ensure the `-DVTK_GROUP_ENABLE_Web:STRING=WANT` flag is enabled when building VTK. This is the default for the wheels on PyPI at this time, but not the distribution on `conda-forge` at this time

**Comment by banesullivan** [comment]
In hidsight, we not error out on the import error in `[trame-vtk/trame_vtk/modules/vtk/__init__.py](https://github.com/Kitware/trame-vtk/blob/c9b7cef7ebf897763f2424416cff4c875b526f12/trame_vtk/modules/vtk/__init__.py#L1-L8)`? It seems like a hard requirement for this whole subpackage, so why not error here?

**Comment by jourdain** [comment]
Because VTK is not a requirement when using just vtk.js.

**Comment by banesullivan** [comment]
Ah right. Then I suggest refactoring this subpackage to isolate parts that are dependent on `vtk`. I'm happy to take this on and will try to open a PR when I get some free cycles

**Comment by jourdain** [comment]
You can through an exception when those classes get instantiated if vtkWeb is not available:
- https://github.com/Kitware/trame-vtk/blob/master/trame_vtk/widgets/vtk/common.py#L331
- https://github.com/Kitware/trame-vtk/blob/master/trame_vtk/widgets/vtk/common.py#L493
- https://github.com/Kitware/trame-vtk/blob/master/trame_vtk/widgets/vtk/common.py#L606
