### ISSUE TITLE
VTK_LONG_LONG (int64) unsupported

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame-vtk#21]
Just realized that numpy's dtype `int64` maps to VTK's `VTK_LONG_LONG` which the web serializer module in VTK is failing to handle. Being that (on my system), the default for `numpy.arange` is `int64` this is a pretty pressing issue we should patch.

I'm not sure what JS type this maps to though...

We definitely need to patch this upstream in VTK, but I'm opening the issue here to patch more quickly

`VTK_LONG_LONG`  and `VTK_UNSIGNED_LONG_LONG` definitions:

https://github.com/Kitware/VTK/blob/aaa1eb770f0de3b86382fd0bad99d4a5755318bd/Common/Core/vtkType.h#L63-L64

Indeed, `16` and `17` are missing from `arrayTypesMapping`:

https://github.com/Kitware/VTK/blob/aaa1eb770f0de3b86382fd0bad99d4a5755318bd/Web/Python/vtkmodules/web/__init__.py#L3-L20

And here is at least a simple example with PyVista where this fails:

```py
import numpy as np
import pyvista as pv

mesh = pv.Sphere()
mesh.cell_data['foo'] = np.arange(mesh.n_cells)

plotter = pv.Plotter()
plotter.add_mesh(mesh, scalars='foo')
plotter.show()
```

```
File /opt/miniconda3/envs/pyvista-dev/lib/python3.9/site-packages/vtkmodules/web/render_window_serializer.py:347, in getArrayDescription(array, context)
    344 if not array:
    345     return None
--> 347 pMd5 = digest(array)
    348 context.cacheDataArray(
    349     pMd5, {"array": array, "mTime": array.GetMTime(), "ts": time.time()}
    350 )
    352 root = {}

File /opt/miniconda3/envs/pyvista-dev/lib/python3.9/site-packages/vtkmodules/web/render_window_serializer.py:322, in digest(array)
    319 if record and record["mtime"] == array.GetMTime():
    320     return record["sha"]
--> 322 record = {"sha": hashDataArray(array), "mtime": array.GetMTime()}
    324 dataArrayShaMapping[objId] = record
    325 return record["sha"]

File /opt/miniconda3/envs/pyvista-dev/lib/python3.9/site-packages/vtkmodules/web/__init__.py:46, in hashDataArray(dataArray)
     44 def hashDataArray(dataArray):
     45     hashedBit = hashlib.md5(memoryview(dataArray)).hexdigest()
---> 46     typeCode = arrayTypesMapping[dataArray.GetDataType()]
     47     return "%s_%d%s" % (hashedBit, dataArray.GetSize(), typeCode)

IndexError: list index out of range
```

**Comment by banesullivan** [comment]
I tried converting to `Int64Array` on the JS side and that'd didn't work...

**Comment by banesullivan** [comment]
Indeed, it appears there is no `Int64Array` type in VTK-js: https://kitware.github.io/vtk-js/docs/structures_DataArray.html#Structure

**Comment by jourdain** [comment]
It is not a vtk-js thing, it is a JavaScript limitation all together...  But they were added ~recently...  
- [BigInt64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array)
- [BigUint64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array)

https://caniuse.com/?search=BigInt64Array

**Comment by banesullivan** [comment]
Hm... I wondering how best to handle this. Should we cast the underlying VTK array to a better-supported type?

**Comment by jourdain** [comment]
Register those new string to match those JS name and add the [here](https://github.com/Kitware/vtk-js/blob/master/Sources/macros.js#L100-L101).  We were probably holding off on wider browser support...

Otherwise, so far we were down casting to 32 bits (u)int on the server side when needed...
