### ISSUE TITLE
RemoteView `still_ratio` is not used initially

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame-vtk#25]
When using a `still_ratio`, the initial view uses a default of `1` and requires some sort of interaction event before the `still_ratio` is used. Take the following example:

```py
import pyvista as pv
from trame.app import get_server
from trame.ui.vuetify import SinglePageLayout
from trame.widgets import vuetify
from trame.widgets.vtk import VtkRemoteView

server = get_server()
state, ctrl = server.state, server.controller

state.trame__title = "PyVista Remote View Ratios"

# -----------------------------------------------------------------------------
pv.set_plot_theme("document")


mesh = pv.Wavelet()

plotter = pv.Plotter(off_screen=True)
actor = plotter.add_mesh(mesh)
plotter.set_background("lightgrey")
plotter.show_grid()
plotter.view_isometric()


# -----------------------------------------------------------------------------
# GUI
# -----------------------------------------------------------------------------

with SinglePageLayout(server) as layout:
    layout.icon.click = ctrl.view_reset_camera
    layout.title.set_text(state.trame__title)

    with layout.toolbar:
        vuetify.VSpacer()

    with layout.content:
        with vuetify.VContainer(
            fluid=True,
            classes="pa-0 fill-height",
        ):
            view = VtkRemoteView(plotter.ren_win, interactive_ratio=2, still_ratio=2)
            ctrl.view_update = view.update
            ctrl.view_reset_camera = view.reset_camera

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

if __name__ == "__main__":
    server.start()
```

https://user-images.githubusercontent.com/22067021/217713501-b0f72b92-9be3-4a18-b8c8-3146c181de36.mov

How can we get the view to use the set `still_ratio` on initialization

See also https://github.com/brendanjmeade/kale/issues/10

**Comment by jourdain** [comment]
Ah that is interesting. That `still_ratio` was not really meant to be go beyond 1 (at least initially).

I guess, I just need to look at the code path to make sure things get set in the right order... ;-)

**Comment by banesullivan** [comment]
> That still_ratio was not really meant to be go beyond 1 (at least initially).

Really? I'm using values of 2 and even up to 4 regularly to add "crispness" to the image

**Comment by jourdain** [comment]
Usually you want the window to match the space available not make it bigger. But there is nothing wrong to bump the resolution beyond the space you have available. 

Anyway, I'm not saying we should not support number more than 1, but at least that is where it is coming from and why we always start with 1.

**Comment by banesullivan** [comment]
Makes sense. I'm wondering if `vtkWindowToImageFilter` and it's `SetScale()` should be used if the ratio/scale is greater than 1?

**Comment by jourdain** [comment]
That would not work because the scale in `vtkWindowToImageFilter` is an integer.

**Comment by jourdain** [comment]
I mean there is no technical issue here. I was just explaining the history and the why.
