### ISSUE TITLE
Client rendering color rescale issue

### ISSUE THREAD

**Issue by psavery** [Kitware/trame-vtk#38]
This is in reference to [this discussion on pyvista](https://github.com/pyvista/pyvista/discussions/4022).

If you run his example script, and click "Load Model", you get this image:

![image](https://user-images.githubusercontent.com/9558430/230125432-38346b5f-dbd0-4e7b-b206-962778d759fa.png)

If you then click "Load Scalars", the desired output is the following:

![image](https://user-images.githubusercontent.com/9558430/230125676-f93c1255-a086-469d-bde8-a1b112bd4d3e.png)

However, instead, you get this:

![image](https://user-images.githubusercontent.com/9558430/230125555-c08c7d95-2194-483d-868d-a300a2b674df.png)

But, if you then refresh the web page, you then get the correct image.

It appears that the colors are not getting rescaled properly. @jourdain, is this potentially an issue with updating from a delta state?

Note that if we change the viewer mode to "server" instead of "client", it works properly.

**Comment by jourdain** [comment]
Yes we will need to see why the delta update is not properly working in that case.

**Comment by jourdain** [comment]
Posted the required fix on the PyVista discussion since it is PyVista related.

FYI @banesullivan
