### ISSUE TITLE
BUG: `axes_actor_serializer` raises unexpected `vtkTransform` `AttributeError`

### ISSUE THREAD

**Issue by user27182** [Kitware/trame-vtk#50]
The following line of code
https://github.com/Kitware/trame-vtk/blob/487c4c03054c5a6dad3a671760d53a2375d3119f/trame_vtk/modules/vtk/serializers/actors.py#L320
unexpectedly raises 
```python 
AttributeError: 'vtkmodules.vtkCommonTransforms.vtkMatrixToLinearTr' object has no attribute 'GetTranspose
```
for valid transforms, e.g. [`vtkMatrixToLinearTransform`](https://vtk.org/doc/nightly/html/classvtkMatrixToLinearTransform.html), which do not implement `GetTranspose`.

This error is raised, for example, when implicitly setting `UserTransform` via `SetUserMatrix`. 
E.g. to reproduce the bug, do:
```python
from vtk import vtkAxesActor, vtkMatrix4x4
# Create actor with user matrix
actor = vtkAxesActor()
matrix = vtkMatrix4x4()
actor.SetUserMatrix(matrix)

# Apply transform
user_matrix = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
if actor.GetUserTransform():
    matrix = vtkMatrix4x4()
    actor.GetUserTransform().GetTranspose(matrix)
    for i in range(4):
        for j in range(4):
            idx = i + 4 * j
            user_matrix[idx] = matrix.GetElement(j, i)
```

This bug showed up recently in PyVista CI testing for PR [pyvista#5019](https://github.com/pyvista/pyvista/pull/5029). Here's a [link](https://github.com/pyvista/pyvista/actions/runs/6434397659/job/17473554431?pr=5029#step:11:1100)  to the `AttributeError` being raised in the test. The cause of the error was traced back to the fact that the axes internally make a call to `actor.SetUserMatrix(matrix)` exactly as shown above.

A suggested fix is to replace:
https://github.com/Kitware/trame-vtk/blob/487c4c03054c5a6dad3a671760d53a2375d3119f/trame_vtk/modules/vtk/serializers/actors.py#L318-L320
with:
``` python
if actor.GetUserMatrix():
    matrix = actor.GetUserMatrix()
    matrix.Transpose()
```

**Comment by jourdain** [comment]
Thanks for that detailed report and suggested fix.

**Comment by jourdain** [comment]
Would you want to do a PR with a commit message like `fix(serializer): Better handling of actor user matrix`?
