### ISSUE TITLE
reading pvd files with pyvista, flashing red and blue.

### ISSUE THREAD

**Issue by MarinsLucas** [Kitware/trame-vtk#56]
I've been working in a project to integrate a scientific program with trame in web. The output of our program are .vtu and .pvd files. To visualize it in trame, I tried to use pyvista to read the pvd and iterate foreach vtu file. The problem occurs while updating from one file to the next one: the whole mesh flashes red or blue. How could I fix my problem? I should use another way other than Pyvista? 

All vtu files have the same mesh, only the scalars are changing. I think the problem occurs updating the colormap. What do you think?

**Comment by banesullivan** [comment]
Drive-by comment: this sounds like a PyVista usage issue, and I want to encourage you to participate in PyVista's community discussions, which may have more eyes: https://github.com/pyvista/pyvista/discussions

Otherwise, could you share some working code for us to run with/reproduce this?
