### ISSUE TITLE
How to select cells using paraview.simple

### ISSUE THREAD

**Issue by MarinsLucas** [Kitware/trame-vtk#58]
I'm using paraview.simple to read and display PVD files. In Paraview, there is a really useful tool called "Plot Selection Over Time", which I would like to use in my trame application. How can I make selections with the mouse in this case?

Another question would be to plot this graph, I thought about using a new VContainer from the trame.vuetify library, but it is located below the original container.

**Comment by jourdain** [comment]
Too many questions and a bit complex to go over in an issue or discussion.

1. Need to create a widget with the proxy API
2. Use VRow and VCol
