### ISSUE TITLE
Trying to play animation using paraview.simple

### ISSUE THREAD

**Issue by MarinsLucas** [Kitware/trame-vtk#59]
I'm creating a PVD file viewing tool. I'm using paraview.simple to read and display my files, but I can't execute the animation. When I run it, only the last frame is displayed in the browser.
How can I do this? Do you have an example similar to what I'm trying to do?

**Comment by jourdain** [comment]
This was already answered in the trame discussion and there is [an example](https://github.com/Kitware/trame/tree/master/examples/07_paraview/TimeAnimation) about exactly that.
