### ISSUE TITLE
No tests?

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame-vtk#6]
There are no automated tests of this package - what would testing look like with trame?

**Comment by jourdain** [comment]
It depend what you want to test. You can validate the python infrastructure without any web involved.
For the UI, it could be done on the JS side itself.

**Comment by banesullivan** [comment]
We should probably implement some tests to at least start validating the Python infrastructure here

**Comment by jourdain** [comment]
You can write your test [here](https://github.com/Kitware/trame-vtk/tree/master/tests)

**Comment by jourdain** [comment]
Something about add/remove actor for the geometry extract would be great.
