### ISSUE TITLE
examples/07_paraview/Picking not working?

### ISSUE THREAD

**Issue by AliE89** [Kitware/trame-vtk#66]
Hi Sebastien,

I was playing around with the examples and noted that **examples/07_paraview/Picking** is (maybe) misbehaving. Box selections look right, but hoverOnPoint/Cell is not displaying any tooltip with info as it happens in pv. 

Cheers

**Comment by jourdain** [comment]
I don't know what you mean. The hover is not activated in that example. Also the tooltip will have to be managed via some web ui.

Moreover you can find VTK example doing hover picking [here](https://github.com/Kitware/trame-vtk/blob/master/examples/validation/PickingRemoteView.py). The only thing is that the example just resolve the actor not the point info, but the basic gist is there...
